app2/urls.py
from django.urls import path
from . import views

app_name = "app2"
urlpatterns = [
    path('', views.Home, name="Home")

]

testapp/urls.py
from django.urls import path
from . import views

app_name = "testapp"
urlpatterns = [
    path('', views.Test, name="Test"),
    path('contact', views.contact, name="Contact"),
    path('about', views.about, name="About"),
    path('add', views.add, name="Add"),
    path('view', views.view, name="View"),
    path('sliders', views.sliders, name="Sliders"),

    path('delete/<id>', views.delete, name="Delete"),
    path('insert', views.insert, name="Insert"),
    path('edit/<id>', views.edit, name="Edit"),

    path('search', views.search, name="Search"),

    path('register', views.SignUp.as_view(), name="Register"),
    path('login', views.UserLogin.as_view(), name="Login"),
    path('logout', views.Logout, name="Logout")
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("testapp.urls")),
    path('settings', include("app2.urls"))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#install Pillow (pip install Pillow)

app2/models.py
from django.db import models

# Create your models here.

testapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

# classes: structure/how something appears/the design/blueprint

# models represent tables in the db

class Students(models.Model):
    name = models.CharField(max_length=20, blank=False, null=False)
    email = models.EmailField()
    phone = models.IntegerField()
    image = models.ImageField(upload_to="uploads/images", default="uploads/images/profile.png")


    def __str__(self):
        return self.name

class Slider(models.Model):
    text = models.CharField(max_length=200, blank=False, null=False)
    text1 = models.CharField(max_length=200, blank=False, null=False)
    image = models.ImageField(upload_to="uploads/sliders", default="uploads/sliders/profile.png")

    def __str__(self):
        return self.text

class CustomUser(AbstractUser):
    year = models.PositiveIntegerField(blank=True, null=True)



# any minute you modify the models file, you MUST make and run migrations

# python manage.py makemigrations: make migrations: create table(model) in the database

# python manage.py migrate: running migrations

app2/views.py
from django.shortcuts import render


def Home(request):
    return render(request, 'hhome.html', {'navbar': 'settings'})
# Create your views here.

testapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages

from .models import Students, Slider
from django.core.paginator import Paginator

from django.views.generic import CreateView
from . models import CustomUser
from .form import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required





def contact(request):
    return render(request, 'Tes.html', {'navbar': 'contact'})


def about(request):
    return render(request, 'about.html', {'navbar': 'about'})


def add(request):
    return render(request, 'add.html', {'navbar': 'add'})


def view(request):

    paginate = Paginator(Students.objects.all().order_by('name'), 2)
    page = request.GET.get('page')
    data = paginate.get_page(page)
    return render(request, 'view.html', {'navbar': 'view', 'data': data})

#def view(request):
    #data = Students.objects.all()
    #return render(request, 'view.html', {'navbar': 'view', 'data': data})


def delete(request, id):
    student = Students.objects.get(id=id)
    student.delete()
    messages.warning(request, 'Entry was successfully deleted')

    return redirect("/view")

def insert(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')

        if len(request.FILES) !=0:
            image = request.FILES['image']
        query = Students(name=name, email=email, phone=phone, image=image)
        query.save()
        messages.success(request, 'Data added successfully!')
        return redirect("/view")
    return redirect("/view")

def edit(request, id):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        image = request.FILES['image']

        student = Students.objects.get(id=id)

        student.name = name
        student.email = email
        student.phone = phone
        student.image = image

        student.save()
        messages.success(request, 'Data updated successfully!')
        return redirect("/view")

    student = Students.objects.get(id=id)
    return render(request, 'edit.html', {'student':student})

def sliders(request):
    slides = Slider.objects.all()
    return render(request, 'sliders.html', {'navbar' : 'slider', 'slides': slides})

def search(request):
    if request.method == 'GET':
        query = request.GET.get('query')
        if query:
            student = Students.objects.filter(name__icontains=query)
            return render(request, 'search.html', {'data':student})

        return render(request, 'search.html')

#CLASS BASED VIEWS

class SignUp(CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('testapp:Login')
    template_name = 'register.html'

class UserLogin(LoginView):
    template_name = 'login.html'

@login_required
def Test(request):
    return render(request, 'pages/home.html', {'navbar': 'home'})

def Logout(request):
    logout(request)
    return redirect('/login')

app2/templates/hhome.html
{% extends 'layout.html' %}

{% block body %}
    <title>Settings</title>

    <div class="container">
        <br>
        <hr>
        <br>
        <p>This is the settings app</p>
        <br>
        <hr>
        <br>
    </div>

{% endblock %}

testapp/templates/Tes.html
{% extends 'layout.html' %}
{% block body %}

    <title>Contact</title>

    <div class="container">
        <br>
        <hr>
        <br>
        <p>This is the contact page</p>
        <br>
        <hr>
        <br>
    </div>

{% endblock %}

testapp/templates/about.html
{% extends 'layout.html' %}
{% block body %}

    <title>About</title>

    <div class="container">
        <br>
        <hr>
        <br>
        <p>This is the about page</p>
        <br>
        <hr>
        <br>
    </div>

{% endblock %}

testapp/templates/add.html
{% extends 'layout.html' %}
{% block body %}
{% load static %}

    <title>Add Data</title>

    {# name, email, phone, image #}
<div class="container">
    <h2>Add Student</h2>
    <hr>
    <br>
    <div class="row">
        <div class="col-md-6">
            <form action="/insert" method="POST" enctype="multipart/form-data">

                {% csrf_token %}

              <div class="mb-3">
                <label class="form-label">Name</label>
                <input type="text" name="name" class="form-control" placeholder="Name" required>
              </div>
              <div class="mb-3">
                <label class="form-label">Email</label>
                <input type="email" name="email" class="form-control" placeholder="Email" required>
              </div>
              <div class="mb-3">
                <label class="form-label">Phone</label>
                <input type="number" name="phone" class="form-control" placeholder="Phone" required>
              </div>
                <div class="mb-3">
                <label class="form-label">Image</label>
                <input type="file" accept="image/png, image/gif, image/jpeg" name="image" class="form-control" required>
              </div>

                <input type="submit" class="form-control btn btn-success">

            </form>
        </div>
    </div>

    <br><br>
    <hr>
</div>

{% endblock %}

testapp/templates/edit.html
{% extends 'layout.html' %}
{% block body %}
{% load static %}

    <title>Edit Data</title>

    {# name, email, phone, image #}
<div class="container">
    <h2>Edit {{ student.name }}'s Data</h2>
    <hr>
    <br>
    <div class="row">
        <div class="col-md-6">
            <form action="" method="POST" enctype="multipart/form-data">

                {% csrf_token %}

              <div class="mb-3">
                <label class="form-label">Name</label>
                <input type="text" name="name" class="form-control" placeholder="Name" value="{{ student.name }}" required>
              </div>
              <div class="mb-3">
                <label class="form-label">Email</label>
                <input type="email" name="email" class="form-control" placeholder="Email" value="{{ student.email }}" required>
              </div>
              <div class="mb-3">
                <label class="form-label">Phone</label>
                <input type="number" name="phone" class="form-control" placeholder="Phone" value="{{ student.phone }}" required>
              </div>
                <div class="mb-3">
                <label class="form-label">Image</label><br>
                    <img src="/media/{{ student.image }}" alt="{{ student.name }}" width="200"><br>
                <input type="file" accept="image/png, image/gif, image/jpeg" name="image" class="form-control" required>
              </div>


                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Submit</button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        Are you sure you want to edit?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-success">
                      </div>
                    </div>
                  </div>
                </div>

            </form>
        </div>
    </div>

    <br><br>
    <hr>
</div>

{% endblock %}

testapp/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link  {% if navbar == 'home' %} active {% endif %}" aria-current="page" href="{% url 'testapp:Test' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if navbar == 'about' %} active {% endif %}" aria-current="page" href="{% url 'testapp:About' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  {% if navbar == 'contact' %} active {% endif %}" aria-current="page" href="{% url 'testapp:Contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  {% if navbar == 'settings' %} active {% endif %}" aria-current="page" href="{% url 'app2:Home' %}">Settings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  {% if navbar == 'add' %} active {% endif %}" aria-current="page" href="{% url 'testapp:Add' %}">Add Data</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  {% if navbar == 'view' %} active {% endif %}" aria-current="page" href="{% url 'testapp:View' %}">View Data</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  {% if navbar == 'sliders' %} active {% endif %}" aria-current="page" href="{% url 'testapp:Sliders' %}">Sliders</a>
            </li>
          <li class="nav-item">
              <a class="nav-link " aria-current="page" href="{% url 'testapp:Logout' %}">Logout</a>
            </li>
          </ul>
          <form action="{% url 'testapp:Search' %}" class="d-flex" role="search" method="get">
            <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    {% block body %}



    {% endblock %}

    <footer>
        <a href="">Crafted by Enola</a>
    </footer>

</body>
</html>

testapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>

    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="Submit">Sign In</button>
    </form>
</body>
</html>

testapp/templates/pages/home.html
{% extends 'layout.html' %}
{% block body %}
{% load  static %}

    <title>Home</title>

    <div class="container">
        <br>
        <hr>
        <br>
        <p class="one">This is the home page</p>
        <br><br>
        <input type="text" class="form-control">
        <br><br>
        <button class="btn btn-success">Accept</button>
        <br><br>
        <img src="{% static 'images/php.jpeg' %}" alt="">
        <br>
        <hr>
        <br>
    </div>

{% endblock %}

testapp/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <h2>Register</h2>

    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="Submit">Sign Up</button>
    </form>
</body>
</html>

testapp/templates/search.html
{% extends 'layout.html' %}
{% block body %}
{% load static %}
    <title>View Data</title>

    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <br>
            <h2>Search Results</h2>
            <hr>
            <hr>
            <br>
            {% if data %}
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Phone</th>
                  <th class="scope">Image</th>
                  <th class="scope">Edit</th>
                  <th class="scope">Delete</th>
                </tr>
              </thead>
              <tbody>
              {% for student in data %}
                  <tr>
                      <th scope="row">{{ student.id }}</th>
                      <td>{{ student.name }}</td>
                      <td>{{ student.email }}</td>
                      <td>{{ student.phone }}</td>
                      <td><img src="media/{{ student.image }}" alt="{{ student.name }}" width="100"></td>
                      <td>
                          <a href="/edit/{{ student.id }}" class="btn btn-warning">Edit</a>
                      </td>
                      <td>
                          <!-- Implement a modal -->
                          <!--<a href="" class="btn btn-danger">Delete</a>-->
                          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</button>

                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                  </div>
                                  <div class="modal-body">
                                    <p>Are you sure you'd like to delete {{ student.name }}'s data?</p>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                                    <a href="/delete/{{ student.id }}" class="btn btn-success">Yes</a>
                                  </div>
                                </div>
                              </div>
                            </div>
                      </td>
                    </tr>

              {% endfor %}

              </tbody>
            </table>

            <br>
            <hr>
            <br>
            <br>
            <br>
        </div>
           <br>
            <hr>
            <br>
            <h2>Card</h2>
            <hr>
            <br>

            <div class="row" style="width: 100%">
                {% for student in data %}
                    <div class="col-md-3 m-2">
                        <div class="card">
                          <img src="media/{{ student.image }}" class="card-img-top" alt="{{ student.name }}" style="width: 100%">
                          <div class="card-body">
                            <h5 class="card-title">{{ student.name }}</h5>
                            <p class="card-text">{{ student.email }}</p>
                            <a href="#" class="btn btn-primary">{{ student.phone}}</a>
                          </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <br>
            <hr>
            <br>
            <br>
            </div>
                    {% else %}

                    <h4>No record Found</h4>

            {% endif %}
    </div>

{% endblock %}

testapp/templates/sliders.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}

    <title>Sliders</title>
    
    <div class="container">
        <div id="carouselExampleCaptions" class="carousel slide">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">

              {% for slide in slides %}

                <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
                  <img src="/media/{{ slide.image }}" class="d-block w-100" alt="...">
                  <div class="carousel-caption d-none d-md-block">
                    <h5>{{ slide.text}}</h5>
                    <p>{{ slide.text1}}</p>
                  </div>
                </div>

              {% endfor %}

            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
    </div>

{% endblock %}

testapp/templates/view.html
{% extends 'layout.html' %}
{% block body %}
{% load static %}
    <title>View Data</title>

    <div class="container">
        <div class="row">
            <div class="col-md-9">
            <h2>Students</h2>
            <hr>
            <h3>Tabular Format</h3>
            <hr>
            <br>

            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Phone</th>
                  <th class="scope">Image</th>
                  <th class="scope">Edit</th>
                  <th class="scope">Delete</th>
                </tr>
              </thead>
              <tbody>
              {% for student in data %}
                  <tr>
                      <th scope="row">{{ student.id }}</th>
                      <td>{{ student.name }}</td>
                      <td>{{ student.email }}</td>
                      <td>{{ student.phone }}</td>
                      <td><img src="media/{{ student.image }}" alt="{{ student.name }}" width="100"></td>
                      <td>
                          <a href="/edit/{{ student.id }}" class="btn btn-warning">Edit</a>
                      </td>
                      <td>
                          <!-- Implement a modal -->
                          <!--<a href="" class="btn btn-danger">Delete</a>-->
                          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</button>

                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                  </div>
                                  <div class="modal-body">
                                    <p>Are you sure you'd like to delete {{ student.name }}'s data?</p>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                                    <a href="/delete/{{ student.id }}" class="btn btn-success">Yes</a>
                                  </div>
                                </div>
                              </div>
                            </div>
                      </td>
                    </tr>

              {% endfor %}

              </tbody>
            </table>
            <br>
            <hr>
            <br>
            <br>
            <br>
        </div>
           <br>
            <hr>
            <br>
            <h2>Grid Display</h2>
            <hr>
            <br>

            <div class="row" style="width: 100%">
                {% for student in data %}
                    <div class="col-md-3 m-2">
                        <div class="card">
                          <img src="media/{{ student.image }}" class="card-img-top" alt="{{ student.name }}" style="width: 100%">
                          <div class="card-body">
                            <h5 class="card-title">{{ student.name }}</h5>
                            <p class="card-text">{{ student.email }}</p>
                            <a href="#" class="btn btn-primary">{{ student.phone}}</a>
                          </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <br>
            <hr>
            <br>
            <br>
            </div>
    </div>

{% endblock %}